### ISSUE TITLE
Shouldn't try to register CentOS Atomic Host

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/adb-vagrant-registration#74] opened 2016-03-29 19:41 UTC
It seems when I try to bring up a CentOS Atomic host ([link](https://atlas.hashicorp.com/centos/boxes/atomic-host)) and I have the vagrant-registration plugin installed then I get prompted to register the machine. We probably need to handle this better:

```
vanilla-c7atomic: Would you like to register the system now (default: yes)? [y|n]
```

Versions: I really don't know what versions of software are being used. I have them installed in the system but they are also in the vagrant plugins directories. It seems that vagrant upgrades all plugins when you just install a new one etc.. Here is what I have:

```
$ rpm -q vagrant vagrant-libvirt vagrant-registration
vagrant-1.7.2-12.fc22.noarch
vagrant-libvirt-0.0.26-3.fc22.noarch
vagrant-registration-1.1.0-2.fc22.noarch
$ ls /guests/vagrant.d/gems/gems/ | grep -P "vagrant-libvirt|vagrant-registration"
vagrant-libvirt-0.0.31
vagrant-registration-1.2.1
```

**Comment by bexelbie** [comment] 2016-08-18 09:43
Closing as duplicate of #89 even though #89 came later.

**Closed by bexelbie** 2016-08-18 09:43 UTC
